### ISSUE TITLE
some clarifications

### ISSUE THREAD

**Issue by l3r8yJ** [tracehubpm/code-review-action#70]
@h1alexbel can you please, explain what's going on in repo from moment of start of GHA and during the whole lifecycle

**Comment by h1alexbel** [comment]
@l3r8yJ sure.

According to `core-review.yml`:

```yml
name: code-review
on:
 pull_request_review:
   types: submitted
permissions:
  pull-requests: write
  contents: read
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker://tracehub/code-review-action:latest
        with:
          openai_token: ${{ secrets.OPENAI_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

once pull request review was submitted (approved), GitHub _starts the GitHub Action Job_ according [action.yml](https://github.com/tracehubpm/code-review-action/blob/master/action.yml) file.

There, we have `runs` section:

https://github.com/tracehubpm/code-review-action/blob/8fd349ca5806a557bd39f9d0020d89341c32dc50/action.yml#L27-L29

GHA pulls image from `docker://tracehub/code-review-action:latest`

you can check our [Dockerfile](https://github.com/tracehubpm/code-review-action/blob/master/Dockerfile) for building this image.

Image pushed to the DockerHub using `@rultor release`:

https://github.com/tracehubpm/code-review-action/blob/8fd349ca5806a557bd39f9d0020d89341c32dc50/.rultor.yml#L10-L13

in `release` profile we prepare JAR with dependencies:

https://github.com/tracehubpm/code-review-action/blob/8fd349ca5806a557bd39f9d0020d89341c32dc50/pom.xml#L325-L356
